// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueuedStatus } from "./QueuedStatus";

export type AnalysisTask = {
  file_hash: string;
  title: string;
  artist: string;
  status: QueuedStatus;
};
