// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInstallStatus } from "./ModelInstallStatus";

/**
 * A read-only snapshot used by the UI to explain why analysis is available
 * or unavailable. Merely loading this value never downloads or changes
 * anything on disk.
 */
export type AnalysisRuntimeStatus = {
  ready: boolean;
  ffmpegAvailable: boolean;
  uvAvailable: boolean;
  systemPythonAvailable: boolean;
  managedRuntimeAvailable: boolean;
  analyzerAvailable: boolean;
  pitchModelAvailable: boolean;
  backendModelsAvailable: boolean;
  selectedModelsAvailable: boolean;
  selectedModels: Array<string>;
  models: Array<ModelInstallStatus>;
  computeBackend: string;
  ffmpegPath: string | null;
  uvPath: string | null;
  systemPythonPath: string | null;
  missing: Array<string>;
};
