// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachePaths } from "./CachePaths";
import type { LibrarySource } from "./LibrarySource";

export type AppConfig = {
  data_path: string | null;
  cache_paths: CachePaths | null;
  library_source: LibrarySource | null;
  /**
   * Preferred folder shown by every export dialog. Individual exports may
   * still choose another destination through Save As.
   */
  export_path: string | null;
  fullscreen: boolean | null;
  dark_mode: boolean | null;
  /**
   * Python AI runtime selected during setup: `cpu`, `cuda`, or `intel`.
   * Changing it requires re-running setup so the virtualenv is rebuilt.
   */
  compute_backend: string | null;
  whisper_model: string | null;
  beam_size: number | null;
  batch_size: number | null;
  separator: string | null;
  asr_engine: string | null;
  align_backend: string | null;
  /**
   * Pitch/frequency-analysis model. Kept explicit even while RMVPE is the
   * only supported option so the settings and download API can evolve.
   */
  pitch_model: string | null;
  vocal_detection_threshold_pct: number | null;
  auto_analyze: boolean | null;
  song_list_view: string | null;
  language_overrides: { [key in string]: string } | null;
};
