// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartReadiness = {
  ready: boolean;
  authoring_ready: boolean;
  missing: Array<string>;
  blocked_reason: string | null;
  can_repair_pitch: boolean;
};
