// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The compute runtime selected before installing the Python environment.
 * It is deliberately explicit: silently picking CUDA on a mixed-GPU system
 * can download several GB of the wrong runtime.
 */
export type ComputeBackend = "cpu" | "cuda" | "intel";
