// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The local folder Uta Studio scans for source audio and video files.
 */
export type LibrarySource = { kind: "folders"; paths: Array<string> };
