// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A concrete, user-visible model family that can be prepared independently.
 * The selected variant (for example the Whisper size or separator backend)
 * is always read from `AppConfig` when the job starts, so a stale UI cannot
 * accidentally download a model that is no longer selected.
 */
export type ModelDownloadTarget =
  | "whisper"
  | "whisper_language_detection"
  | "parakeet"
  | "separator"
  | "alignment"
  | "pitch"
  | "open_vino_whisper";
