// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDownloadTarget } from "./ModelDownloadTarget";

export type ModelInstallStatus = {
  target: ModelDownloadTarget;
  label: string;
  description: string;
  available: boolean;
};
