// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachePaths } from "./CachePaths";
import type { ComputeBackend } from "./ComputeBackend";
import type { ModelDownloadTarget } from "./ModelDownloadTarget";

export type SetupFolders = {
  dataPath: string | null;
  cachePaths: CachePaths | null;
  computeBackend: ComputeBackend;
  modelTarget: ModelDownloadTarget | null;
};
