// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupStep } from "./SetupStep";
import type { SetupTaskState } from "./SetupTaskState";

export type SetupTask = {
  step: SetupStep;
  label: string;
  state: SetupTaskState;
  /**
   * Bytes received for direct downloads, or bytes currently installed in
   * the virtualenv while a package job is running. `None` means that the
   * upstream tool did not report a meaningful figure.
   */
  downloaded_bytes: bigint | null;
  /**
   * The server's Content-Length where available. Package resolvers usually
   * do not expose a reliable total, so this is intentionally optional.
   */
  total_bytes: bigint | null;
};
