// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongOrigin } from "./SongOrigin";
import type { TranscriptSource } from "./TranscriptSource";
import type { UsdxBundle } from "./UsdxBundle";

export type Song = {
  path: string;
  file_hash: string;
  title: string;
  artist: string;
  album: string;
  duration_secs: number;
  album_art_path: string | null;
  is_analyzed: boolean;
  language: string | null;
  transcript_source: TranscriptSource | null;
  key: string | null;
  override_key: string | null;
  tempo: number;
  key_offset: number;
  is_video: boolean;
  usdx: UsdxBundle | null;
  origin: SongOrigin;
  /**
   * True when a provided LRC is authored over the original mix without
   * creating separate stems.
   */
  no_stems: boolean;
  /**
   * True only when every artifact required by package export exists.  This
   * is refreshed from disk when a song is read; unlike `is_analyzed`, it
   * does not mistake an older lyrics-only analysis for a finished chart.
   */
  authoring_ready: boolean;
  authoring_missing: Array<string>;
  /**
   * Source charts are edited at their original key and tempo. Export can
   * still be ready while the editor asks the user to reset a live shift.
   */
  editor_ready: boolean;
  editor_blocked_reason: string | null;
};
