"""Offline audio model catalog, parameter schema, and processing plans."""

from .catalog import (
    DEFAULT_LEGACY_KARAOKE_MODEL_ID,
    REQUIRED_MODEL_IDS,
    AudioModelCatalog,
    ModelFileSpec,
    ModelSpec,
    catalog_path,
    installed_model_dir,
    load_catalog,
    manifest_path,
)
from .errors import (
    AudioProcessingError,
    BackendUnavailableError,
    CatalogError,
    InferenceOutOfMemoryError,
    ModelConfigurationError,
    ModelIntegrityError,
    ModelNotInstalledError,
    OutputContractError,
    ParameterValidationError,
)
from .parameters import ResolvedParameter, ResolvedParameters, resolve_parameters
from .plan import (
    AudioInputReference,
    AudioOutputBinding,
    AudioProcessingPlanSnapshot,
    AudioProcessingStep,
    AudioRuntimeRequest,
    build_chart_analysis_plan,
    build_karaoke_plan,
    build_multistem_plan,
    build_settings_plan,
    legacy_plan_from_separator,
    plan_from_json,
)
from .schema import PARAMETER_SPECS, schema_for

__all__ = [
    "DEFAULT_LEGACY_KARAOKE_MODEL_ID",
    "REQUIRED_MODEL_IDS",
    "AudioInputReference",
    "AudioModelCatalog",
    "AudioOutputBinding",
    "AudioProcessingError",
    "AudioProcessingPlanSnapshot",
    "AudioProcessingStep",
    "AudioRuntimeRequest",
    "BackendUnavailableError",
    "CatalogError",
    "InferenceOutOfMemoryError",
    "ModelConfigurationError",
    "ModelFileSpec",
    "ModelIntegrityError",
    "ModelNotInstalledError",
    "ModelSpec",
    "OutputContractError",
    "PARAMETER_SPECS",
    "ParameterValidationError",
    "ResolvedParameter",
    "ResolvedParameters",
    "build_chart_analysis_plan",
    "build_karaoke_plan",
    "build_multistem_plan",
    "build_settings_plan",
    "catalog_path",
    "installed_model_dir",
    "legacy_plan_from_separator",
    "load_catalog",
    "manifest_path",
    "plan_from_json",
    "resolve_parameters",
    "schema_for",
]
